config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'

  # post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
       Copyright &copy; by <a href="http://www.tirthpatel.net" target="_blank"> Tirth Patel </a>
        </small>
        <nav>
            <ul>
            <li> <%= link_to 'About', about_path %></li>
            </ul>
     </nav>
    </footer>
 </div>

app/views/layouts/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

    <div class='alert alert-<%="#{name}" %> alert-dismissible fade in' >

        <a href="#" class="close" data-dismiss="alert">&times</a>

        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

    </div>

<% end %>

</div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <%= link_to "Blog" , root_path, class: "navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       

        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to  "New Article", new_article_path %></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        <% end %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to  "All categories", categories_path %></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %> </li>
                <% end %>
                
                <% if logged_in? && current_user.admin? %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Create new category", new_category_path %> </li>
                <% end %>

              </ul>
            </li>
      </ul>
      
     <ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

    <li><%= link_to 'Log out', logout_path, data:{"turbo-method": :delete } %></li>

    <li class="nav-item dropdown">

    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbarDropdown"  role="button" data-bs-toggle="dropdown"aria-expanded="false">Your Profile
    <%= "Admin" if current_user.admin? %>
    </a>

    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

    <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>

    <li><%= link_to "View your profile", user_path(current_user) %></li>

    <li><a href="#">Something else here</a></li>

    

    </ul>

    </li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', signup_path %></li>

<% end %>

</ul>


    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  

       <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
    
  </head>

  <body>


    <%= render 'layouts/messages' %>

  <%= render 'layouts/navigation' %>
  <div class = "container">
    <%= yield %>
  </div>
   <%= render 'layouts/footer' %>
   <%= debug(params) if Rails.env.development? %>
  </body>
</html>